// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8MpvlrWbL3zWRiz8biPXpPB7xnWOoiko',
    appId: '1:218809920637:web:f9880bde18b53a5eb25514',
    messagingSenderId: '218809920637',
    projectId: 'beehive-222025',
    authDomain: 'beehive-222025.firebaseapp.com',
    databaseURL: 'https://beehive-222025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beehive-222025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaouwq4KiUl8OHytXlZZOekgp2zWQwjag',
    appId: '1:218809920637:android:d84a5a9e4a0173b8b25514',
    messagingSenderId: '218809920637',
    projectId: 'beehive-222025',
    databaseURL: 'https://beehive-222025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beehive-222025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGBpZgEuQvsS9szd328176kPd80d6wqLQ',
    appId: '1:218809920637:ios:bbc4bcd82a6092d7b25514',
    messagingSenderId: '218809920637',
    projectId: 'beehive-222025',
    databaseURL: 'https://beehive-222025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beehive-222025.firebasestorage.app',
    androidClientId: '218809920637-pcms76bhaqaihaaj9c2qllcbt4kram26.apps.googleusercontent.com',
    iosClientId: '218809920637-0e7aoahlmti9v28mcsju10qau4n4jlrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.beehive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGBpZgEuQvsS9szd328176kPd80d6wqLQ',
    appId: '1:218809920637:ios:bbc4bcd82a6092d7b25514',
    messagingSenderId: '218809920637',
    projectId: 'beehive-222025',
    databaseURL: 'https://beehive-222025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beehive-222025.firebasestorage.app',
    androidClientId: '218809920637-pcms76bhaqaihaaj9c2qllcbt4kram26.apps.googleusercontent.com',
    iosClientId: '218809920637-0e7aoahlmti9v28mcsju10qau4n4jlrm.apps.googleusercontent.com',
    iosBundleId: 'com.example.beehive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8MpvlrWbL3zWRiz8biPXpPB7xnWOoiko',
    appId: '1:218809920637:web:e95dc4cca18cf603b25514',
    messagingSenderId: '218809920637',
    projectId: 'beehive-222025',
    authDomain: 'beehive-222025.firebaseapp.com',
    databaseURL: 'https://beehive-222025-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'beehive-222025.firebasestorage.app',
  );
}
